// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

import {ERC721} from "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import {Base64} from "@openzeppelin/contracts/utils/Base64.sol";
import {Strings} from "@openzeppelin/contracts/utils/Strings.sol";

/**
 * @title On-Chain Garden
 * @author Lucas Serpa
 * @notice A fully on-chain NFT plant: its image and metadata are generated by the
 *         contract itself (no IPFS). Each plant grows as you water it, wilts if you
 *         neglect it, and is born with its own unique look (colors, flower, pot).
 * @dev The art is a base64-encoded SVG built inside `tokenURI`, so the NFT reflects
 *      its live state (growth stage + thirst) on every read. The cosmetic traits come
 *      from a per-plant `seed` fixed at mint. We use cheap on-chain pseudo-randomness
 *      on purpose: the look has no economic value, so there's nothing to gain by
 *      manipulating it — Chainlink VRF would be overkill here.
 */
contract OnChainGarden is ERC721 {
    using Strings for uint256;

    error NotYourPlant();

    /// @dev Packs into a single storage slot (64 + 64 + 64 = 192 bits).
    struct Plant {
        uint64 waterCount; // total waterings -> drives the growth stage
        uint64 lastWatered; // last watering timestamp -> drives "thirsty"
        uint64 seed; // fixed at mint -> drives the unique look
    }

    /// @dev Cosmetic traits, all derived deterministically from a plant's seed.
    struct Art {
        string green; // leaves & stem
        string sky; // background
        string flower; // bloom petals
        string potBody; // pot fill
        string potRim; // pot rim
        uint8 petals; // 4, 5 or 6
        uint8 potShape; // 0 tapered, 1 rounded, 2 square
    }

    // Growth thresholds, measured in number of waterings.
    uint64 public constant SPROUT_AT = 3;
    uint64 public constant PLANT_AT = 6;
    uint64 public constant BLOOM_AT = 10;

    // A plant looks thirsty if it hasn't been watered within this window.
    uint256 public constant THIRSTY_AFTER = 1 days;

    // Palette sizes (named so the modulo math reads clearly and lives in one place).
    uint8 private constant GREEN_COUNT = 6;
    uint8 private constant SKY_COUNT = 6;
    uint8 private constant FLOWER_COUNT = 6;
    uint8 private constant POT_COUNT = 5;
    uint8 private constant MIN_PETALS = 4;
    uint8 private constant PETAL_VARIANTS = 3; // 4, 5 or 6 petals
    uint8 private constant POT_SHAPES = 3;

    uint256 private _nextId;
    mapping(uint256 tokenId => Plant) private _plants;

    event Planted(address indexed owner, uint256 indexed tokenId);
    event Watered(uint256 indexed tokenId, uint64 waterCount);

    constructor() ERC721("On-Chain Garden", "PLANT") {}

    /// @notice Plant a new seed (mints a fresh plant to the caller).
    /// @return tokenId The id of the newly planted NFT.
    function mint() external returns (uint256 tokenId) {
        tokenId = ++_nextId;
        // Cheap per-plant randomness: enough entropy to make looks unique, nothing to exploit.
        uint64 seed = uint64(uint256(keccak256(abi.encodePacked(block.timestamp, block.prevrandao, msg.sender, tokenId))));
        _plants[tokenId] = Plant({waterCount: 0, lastWatered: uint64(block.timestamp), seed: seed});
        _safeMint(msg.sender, tokenId);
        emit Planted(msg.sender, tokenId);
    }

    /// @notice Water your plant: it grows a bit and gets revived if it was thirsty.
    /// @param tokenId The plant to water. Only its owner can water it.
    function water(uint256 tokenId) external {
        if (ownerOf(tokenId) != msg.sender) revert NotYourPlant();

        Plant storage plant = _plants[tokenId];
        plant.waterCount += 1;
        plant.lastWatered = uint64(block.timestamp);

        emit Watered(tokenId, plant.waterCount);
    }

    /// @notice Growth stage of a plant: 0 seed, 1 sprout, 2 plant, 3 bloom.
    function stageOf(uint256 tokenId) public view returns (uint8) {
        uint64 waterCount = _plants[tokenId].waterCount;
        if (waterCount >= BLOOM_AT) return 3;
        if (waterCount >= PLANT_AT) return 2;
        if (waterCount >= SPROUT_AT) return 1;
        return 0;
    }

    /// @notice True when the plant hasn't been watered for a while (it looks wilted).
    function isThirsty(uint256 tokenId) public view returns (bool) {
        return block.timestamp - _plants[tokenId].lastWatered > THIRSTY_AFTER;
    }

    /// @notice The unique seed assigned at mint that determines a plant's look.
    /// @dev Same seed forever -> a plant's colors/shape never change, only its growth does.
    function seedOf(uint256 tokenId) public view returns (uint64) {
        return _plants[tokenId].seed;
    }

    /// @notice Render the SVG art for any seed/state without minting.
    /// @dev Handy for a "preview your plant" UI and for exercising every art branch in tests.
    /// @param seed_ The seed whose look you want to render.
    /// @param stage_ Growth stage to draw (0 seed, 1 sprout, 2 plant, 3 bloom).
    /// @param thirsty_ Whether to draw the wilted (thirsty) variant.
    /// @return The raw SVG markup.
    function previewArt(uint64 seed_, uint8 stage_, bool thirsty_) public pure returns (string memory) {
        return _svg(stage_, thirsty_, _artOf(seed_));
    }

    /// @notice Fully on-chain metadata (base64 JSON) with the live SVG embedded.
    function tokenURI(uint256 tokenId) public view override returns (string memory) {
        _requireOwned(tokenId);

        Plant memory plant = _plants[tokenId];
        uint8 stage = stageOf(tokenId);
        bool thirsty = isThirsty(tokenId);
        Art memory art = _artOf(plant.seed);
        string memory image = Base64.encode(bytes(_svg(stage, thirsty, art)));

        string memory json = string.concat(
            '{"name":"Plant #',
            tokenId.toString(),
            '","description":"A fully on-chain plant that grows when you water it and wilts if neglected.",',
            '"attributes":[',
            '{"trait_type":"Stage","value":"',
            _stageName(stage),
            '"},{"trait_type":"Waterings","value":',
            uint256(plant.waterCount).toString(),
            '},{"trait_type":"Status","value":"',
            thirsty ? "Thirsty" : "Healthy",
            '"},{"trait_type":"Petals","value":',
            uint256(art.petals).toString(),
            '}],"image":"data:image/svg+xml;base64,',
            image,
            '"}'
        );

        return string.concat("data:application/json;base64,", Base64.encode(bytes(json)));
    }

    // ----------------------------------------------------------------
    // Internal art helpers — build the SVG on the fly from the state.
    // ----------------------------------------------------------------

    function _stageName(uint8 stage) internal pure returns (string memory) {
        if (stage == 3) return "Bloom";
        if (stage == 2) return "Plant";
        if (stage == 1) return "Sprout";
        return "Seed";
    }

    /// @dev Splits the seed into independent bytes so the traits don't correlate.
    function _artOf(uint64 seed) internal pure returns (Art memory art) {
        art.green = _greenShade(uint8(seed) % GREEN_COUNT);
        art.sky = _skyShade(uint8(seed >> 8) % SKY_COUNT);
        art.flower = _flowerColor(uint8(seed >> 16) % FLOWER_COUNT);

        uint8 pot = uint8(seed >> 24) % POT_COUNT;
        art.potBody = _potBody(pot);
        art.potRim = _potRim(pot);

        art.petals = MIN_PETALS + (uint8(seed >> 32) % PETAL_VARIANTS);
        art.potShape = uint8(seed >> 40) % POT_SHAPES;
    }

    /// @dev Greens dull and the sky washes out when thirsty; the rest of the look stays.
    function _svg(uint8 stage, bool thirsty, Art memory art) internal pure returns (string memory) {
        string memory green = thirsty ? "#9aa05e" : art.green;
        string memory sky = thirsty ? "#efe9d3" : art.sky;

        return string.concat(
            '<svg xmlns="http://www.w3.org/2000/svg" width="320" height="320" viewBox="0 0 320 320">',
            '<rect width="320" height="320" fill="',
            sky,
            '"/>',
            _body(stage, green, art),
            _pot(art.potShape, art.potBody, art.potRim),
            "</svg>"
        );
    }

    /// @dev The plant itself, drawn differently per stage.
    function _body(uint8 stage, string memory green, Art memory art) internal pure returns (string memory) {
        if (stage == 0) {
            return '<ellipse cx="160" cy="236" rx="9" ry="6" fill="#7a5230"/>';
        }
        if (stage == 1) {
            return string.concat(
                '<rect x="157" y="198" width="6" height="44" fill="', green, '"/>',
                '<ellipse cx="143" cy="212" rx="15" ry="8" fill="', green, '"/>',
                '<ellipse cx="177" cy="206" rx="15" ry="8" fill="', green, '"/>'
            );
        }

        // Stages 2 and 3 share a tall stem with four leaves.
        string memory stem = string.concat(
            '<rect x="157" y="150" width="6" height="92" fill="', green, '"/>',
            '<ellipse cx="138" cy="224" rx="18" ry="10" fill="', green, '"/>',
            '<ellipse cx="182" cy="214" rx="18" ry="10" fill="', green, '"/>',
            '<ellipse cx="138" cy="188" rx="18" ry="10" fill="', green, '"/>',
            '<ellipse cx="182" cy="178" rx="18" ry="10" fill="', green, '"/>'
        );
        if (stage == 2) return stem;

        // Stage 3 tops the stem with a flower whose color and petal count come from the seed.
        return string.concat(stem, _flower(art.petals, art.flower));
    }

    /// @dev Petals laid out around a yellow center; positions are precomputed per count.
    function _flower(uint8 count, string memory color) internal pure returns (string memory) {
        string memory petals;
        if (count == 4) {
            petals = string.concat(
                _petal(160, 108, color), _petal(182, 130, color), _petal(160, 152, color), _petal(138, 130, color)
            );
        } else if (count == 5) {
            petals = string.concat(
                _petal(160, 108, color),
                _petal(181, 123, color),
                _petal(173, 148, color),
                _petal(147, 148, color),
                _petal(139, 123, color)
            );
        } else {
            petals = string.concat(
                _petal(160, 108, color),
                _petal(179, 119, color),
                _petal(179, 141, color),
                _petal(160, 152, color),
                _petal(141, 141, color),
                _petal(141, 119, color)
            );
        }
        return string.concat(petals, '<circle cx="160" cy="130" r="13" fill="#ffd23f"/>');
    }

    function _petal(uint256 cx, uint256 cy, string memory color) internal pure returns (string memory) {
        return string.concat('<circle cx="', cx.toString(), '" cy="', cy.toString(), '" r="12" fill="', color, '"/>');
    }

    /// @dev Three pot silhouettes; the rim sits on top of all of them.
    function _pot(uint8 shape, string memory body, string memory rim) internal pure returns (string memory) {
        string memory pot;
        if (shape == 1) {
            pot = string.concat('<rect x="128" y="252" width="64" height="48" rx="16" fill="', body, '"/>');
        } else if (shape == 2) {
            pot = string.concat('<rect x="128" y="252" width="64" height="48" fill="', body, '"/>');
        } else {
            pot = string.concat('<path d="M122 248 L198 248 L188 300 L132 300 Z" fill="', body, '"/>');
        }
        return string.concat(pot, '<rect x="116" y="240" width="88" height="14" rx="3" fill="', rim, '"/>');
    }

    // --- palettes (kept as small lookups so the colors are easy to read and tweak) ---

    function _greenShade(uint8 i) internal pure returns (string memory) {
        if (i == 0) return "#3fa34d";
        if (i == 1) return "#2e8b57";
        if (i == 2) return "#4caf50";
        if (i == 3) return "#1b7a3d";
        if (i == 4) return "#5bbf5b";
        return "#2f8f57";
    }

    function _skyShade(uint8 i) internal pure returns (string memory) {
        if (i == 0) return "#cdeffc";
        if (i == 1) return "#bfe3ff";
        if (i == 2) return "#d7f0ff";
        if (i == 3) return "#e7f7ff";
        if (i == 4) return "#cfeaff";
        return "#c3e0f5";
    }

    function _flowerColor(uint8 i) internal pure returns (string memory) {
        if (i == 0) return "#ff6b9d";
        if (i == 1) return "#ff8c42";
        if (i == 2) return "#c77dff";
        if (i == 3) return "#ff5d5d";
        if (i == 4) return "#7cc6ff";
        return "#ff4fa3";
    }

    function _potBody(uint8 i) internal pure returns (string memory) {
        if (i == 0) return "#b5651d";
        if (i == 1) return "#a0522d";
        if (i == 2) return "#8d6e63";
        if (i == 3) return "#c1440e";
        return "#6d4c41";
    }

    function _potRim(uint8 i) internal pure returns (string memory) {
        if (i == 0) return "#caa472";
        if (i == 1) return "#c08a5e";
        if (i == 2) return "#b3a39b";
        if (i == 3) return "#e0855e";
        return "#a1887f";
    }
}
